### ISSUE TITLE
Running the region constraints without adaptor not working

### ISSUE THREAD

**Issue by yaseryacoob** [Young98CN/LoRA_Composer#5]
I am trying to run with pipeline_type "sd" so not to use the adaptors but it fails. The option is not consistent in (I also see adaptor_sd). Can you please classify hot to run without the sketch and keypose constraints?

**Comment by Young98CN** [comment]
Oh, I overlooked this when tidying up the code. It is not the flag that controls the model use or not use the condition (like sketch and pose). You can use the ['--image_guidance'](https://github.com/Young98CN/LoRA_Composer/blob/a48a5a597f7a1745825d8971955fc4d4d4c39fa8/inference/region_lora_sample.py#L246C5-L246C70) to activate use condition.
