### ISSUE TITLE
A <ckc>character holding a <wpe>weapon while driving a <mror>motorbike

### ISSUE THREAD

**Issue by Sundragon1993** [Young98CN/LoRA_Composer#6]
Dear team, thank you for the great contribution to the community, I'm wondering if this algorithm could be applied to train a Lora(s) that combines several different concepts like a character holding a gun while driving a motorbike? I have several images depicting each concept separately, but I couldn't find any experiments in your paper that elaborate on how the model handles interactions between such multi-concept scenarios. Could you provide further insights on this?

**Comment by Young98CN** [comment]
Apologies for the delayed response—I’ve been caught up with a tight deadline. We’ve included an [example](https://github.com/Young98CN/LoRA_Composer/blob/3bb5fe696896caedee81710c2860b50981fb5b10/scripts/lora_composer_scripts/paper_result_scripts/lora_composer_real.sh#L49C1-L95C1) in the code that demonstrates the interaction between two persons.

Additionally, we recommend using more refined image conditions (human pose or canny edge) to control the model, as this can potentially lead to improved results.

Thank you for your patience, and feel free to reach out if you have further questions.
